services:
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:3000"
    restart: always
    networks:
      - crowdflow-net
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:${BACKEND_PORT:-8080}:8080"
    restart: always
    networks:
      - crowdflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_CLIENT_ID=91716845059-1l96nahbcu7nb39k1sa9r4ev8p2nitdu.apps.googleusercontent.com
      - DEV_MODE=false
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - crowdflow-net

  nginx:
    image: nginx:alpine
    pull_policy: never
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:${NGINX_PORT:-8000}:80"
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - crowdflow-net

networks:
  crowdflow-net:
    driver: bridge

volumes:
  minio-data:
    driver: local
