import { EventSubmission, DocumentReview, AuditorActivity } from "./types";

export const INITIAL_SUBMISSIONS: EventSubmission[] = [
  {
    id: "SUB-3021",
    eventName: "Neon Nights Festival",
    organizerName: "Aurora Live Events",
    organizerAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-07-08 14:20",
    stage: "Document Verification",
    status: "Pending",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "venue-permit-2026.pdf", category: "Permits & Licenses", status: "VERIFIED" },
      { name: "vendor-contract-catering.pdf", category: "Vendor & Venue Contracts", status: "WAITING REVIEW" },
      { name: "artist-agreement-headliner.pdf", category: "Artist & Talent Agreements", status: "READY" },
    ],
    venue: "Zilker Park, Austin",
    date: "2026-09-12",
    capacity: 4200,
  },
  {
    id: "SUB-3022",
    eventName: "Global Tech Summit 2026",
    organizerName: "Summit Live Events",
    organizerAvatar: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=100&auto=format&fit=crop&q=80",
    category: "Conference",
    submittedAt: "2026-07-07 09:05",
    stage: "Event Validation",
    status: "Pending",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "moscone-center-contract.pdf", category: "Vendor & Venue Contracts", status: "VERIFIED" },
      { name: "insurance-certificate.pdf", category: "Supporting Documents", status: "VERIFIED" },
    ],
    venue: "Moscone Center, SF",
    date: "2026-10-02",
    capacity: 1800,
  },
  {
    id: "SUB-3023",
    eventName: "Riverside Jazz Weekend",
    organizerName: "Nightfall Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-07-05 18:40",
    stage: "Submitted",
    status: "Pending",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: false },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "riverside-park-permit.pdf", category: "Permits & Licenses", status: "WAITING REVIEW" },
    ],
    venue: "Riverside Green, Portland",
    date: "2026-08-22",
    capacity: 1200,
    notes: "Venue layout section incomplete — zones not mapped to capacity.",
  },
  {
    id: "SUB-3018",
    eventName: "Executive Leadership Retreat",
    organizerName: "CrowdFlow Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
    category: "Conference",
    submittedAt: "2026-06-29 11:15",
    stage: "Final Approval",
    status: "Approved",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "retreat-center-contract.pdf", category: "Vendor & Venue Contracts", status: "VERIFIED" },
    ],
    venue: "Cascade Lodge, WA",
    date: "2026-08-01",
    capacity: 150,
  },
  {
    id: "SUB-3011",
    eventName: "Underground Bass Collective",
    organizerName: "Nightfall Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-06-20 20:00",
    stage: "Document Verification",
    status: "Rejected",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "warehouse-lease.pdf", category: "Vendor & Venue Contracts", status: "REJECTED" },
    ],
    venue: "Old Freight Warehouse, Brooklyn",
    date: "2026-07-30",
    capacity: 800,
    notes: "Venue lease document expired prior to event date. Requires renewed lease before resubmission.",
  },
];

export const INITIAL_DOCUMENT_REVIEWS: DocumentReview[] = [
  { id: "DOC-501", fileName: "vendor-contract-catering.pdf", category: "Vendor & Venue Contracts", eventName: "Neon Nights Festival", organizerName: "Aurora Live Events", uploadedAt: "2026-07-08", status: "WAITING REVIEW" },
  { id: "DOC-502", fileName: "riverside-park-permit.pdf", category: "Permits & Licenses", eventName: "Riverside Jazz Weekend", organizerName: "Nightfall Presents", uploadedAt: "2026-07-05", status: "WAITING REVIEW" },
  { id: "DOC-503", fileName: "artist-agreement-headliner.pdf", category: "Artist & Talent Agreements", eventName: "Neon Nights Festival", organizerName: "Aurora Live Events", uploadedAt: "2026-07-06", status: "READY" },
  { id: "DOC-499", fileName: "moscone-center-contract.pdf", category: "Vendor & Venue Contracts", eventName: "Global Tech Summit 2026", organizerName: "Summit Live Events", uploadedAt: "2026-07-01", status: "VERIFIED" },
  { id: "DOC-498", fileName: "insurance-certificate.pdf", category: "Supporting Documents", eventName: "Global Tech Summit 2026", organizerName: "Summit Live Events", uploadedAt: "2026-07-01", status: "VERIFIED" },
  { id: "DOC-490", fileName: "warehouse-lease.pdf", category: "Vendor & Venue Contracts", eventName: "Underground Bass Collective", organizerName: "Nightfall Presents", uploadedAt: "2026-06-19", status: "REJECTED" },
];

export const ACTIVITY_LOG: AuditorActivity[] = [
  { id: "act-1", actor: "You", action: "Approved", detail: "Executive Leadership Retreat cleared final approval and was published.", timestamp: "2h ago" },
  { id: "act-2", actor: "You", action: "Rejected", detail: "Underground Bass Collective rejected — expired venue lease.", timestamp: "1d ago" },
  { id: "act-3", actor: "System", action: "Submitted", detail: "Riverside Jazz Weekend entered the review queue.", timestamp: "2d ago" },
  { id: "act-4", actor: "You", action: "Verified", detail: "Insurance certificate confirmed for Global Tech Summit 2026.", timestamp: "3d ago" },
];
