import { EventSubmission, DocumentReview, AuditorActivity } from "./types";

export const INITIAL_SUBMISSIONS: EventSubmission[] = [
  {
    id: "SUB-3021",
    eventName: "Neon Nights Festival",
    organizerName: "Aurora Live Events",
    organizerAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-07-08 14:20",
    lastUpdated: "2026-07-09 10:00",
    stage: "Document Verification",
    status: "Pending",
    riskLevel: "High",
    complianceScore: 62,
    missingDocs: 3,
    assignedAuditor: "Priya Nair",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "venue-permit-2026.pdf", category: "Permits & Licenses", status: "VERIFIED", uploadDate: "2026-07-08", expiredDate: "2027-01-01", uploadedBy: "Admin Aurora" },
      { name: "vendor-contract-catering.pdf", category: "Vendor & Venue Contracts", status: "WAITING REVIEW", uploadDate: "2026-07-08", uploadedBy: "Admin Aurora" },
      { name: "artist-agreement-headliner.pdf", category: "Artist & Talent Agreements", status: "READY", uploadDate: "2026-07-06", uploadedBy: "Aurora HR" },
      { name: "police-permit.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "fire-dept-permit.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "insurance-policy.pdf", category: "Insurance", status: "MISSING" },
    ],
    venue: "Zilker Park, Austin",
    date: "2026-09-12",
    capacity: 4200,
    ticketSold: 1840,
    organizerDetail: {
      companyName: "Aurora Live Events, LLC",
      businessLicense: "BL-2024-TX-00492",
      pic: "Marcus Chen",
      email: "marcus@auroralive.com",
      phone: "+1 (512) 390-4820",
      address: "820 Congress Ave, Austin TX 78701",
    },
    venueDetail: {
      name: "Zilker Park",
      address: "2100 Barton Springs Rd, Austin, TX 78704",
      capacity: 4500,
      manager: "City of Austin Parks Dept.",
      contact: "+1 (512) 974-6700",
      website: "austintexas.gov/zilkerpark",
      googleMaps: "https://maps.google.com/?q=Zilker+Park+Austin",
      complianceScore: 78,
      checklist: [
        { label: "Venue Ownership Verified", done: true },
        { label: "Maximum Capacity Verified", done: true },
        { label: "Seating Configuration Valid", done: true },
        { label: "Emergency Exit Verified", done: true },
        { label: "Fire Safety", done: false },
        { label: "Crowd Flow Validation", done: false },
        { label: "Acoustic Safety", done: true },
        { label: "Structural Safety", done: true },
        { label: "Parking Area", done: true },
        { label: "Accessibility", done: false },
      ],
    },
    logistics: {
      vendorCount: 8,
      securityCount: 45,
      medicalTeam: 6,
      emergencyTeam: 4,
      vendors: [
        { name: "StageCraft Pro", category: "Stage", status: "Verified", contact: "+1 512 200 1010" },
        { name: "LumineX Lighting", category: "Lighting", status: "Verified", contact: "+1 512 201 2020" },
        { name: "SoundWave AV", category: "Sound", status: "Pending", contact: "+1 512 202 3030" },
        { name: "FoodFest Catering", category: "Food", status: "Pending", contact: "+1 512 203 4040" },
        { name: "MerchHub", category: "Merchandise", status: "Rejected", contact: "+1 512 204 5050" },
        { name: "CleanCrew TX", category: "Cleaning", status: "Verified", contact: "+1 512 205 6060" },
        { name: "SecureGuard", category: "Security", status: "Verified", contact: "+1 512 206 7070" },
      ],
      emergencyPlan: [
        { label: "Ambulance", done: true },
        { label: "Fire Truck", done: false },
        { label: "Emergency Exit", done: true },
        { label: "Evacuation Route", done: true },
        { label: "Assembly Point", done: false },
      ],
    },
    finance: {
      projectedRevenue: 920000,
      platformFee: 46000,
      gatewayFee: 18400,
      taxAmount: 82800,
      netPayout: 772800,
      ticketTiers: [
        { category: "VVIP", price: 850, seats: 150, status: "Active" },
        { category: "VIP", price: 450, seats: 400, status: "Active" },
        { category: "Festival", price: 180, seats: 1800, status: "Active" },
        { category: "Regular", price: 90, seats: 1850, status: "Sold Out" },
      ],
      taxConfig: {
        entertainmentTax: 10,
        ppn: 11,
        region: "Austin, TX",
        taxPercentage: 21,
        regionMatch: true,
        taxApplied: true,
        ppnApplied: false,
      },
      payout: {
        bank: "JP Morgan Chase",
        accountName: "Aurora Live Events LLC",
        accountNumber: "****4821",
        verified: true,
        estimatedPayout: 772800,
      },
      complianceChecklist: [
        { label: "Ticket Price Verified", done: true },
        { label: "Revenue Calculation", done: true },
        { label: "Platform Fee Applied", done: true },
        { label: "Tax Calculation", done: true },
        { label: "Tax Match", done: false },
      ],
    },
    history: {
      activityTimeline: [
        { id: "h1", user: "Marcus Chen", role: "Organizer", action: "Submitted Event", detail: "Initial submission of Neon Nights Festival.", timestamp: "2026-07-08 14:20" },
        { id: "h2", user: "System", role: "Auto", action: "Auto Validation Passed", detail: "Event info, venue layout, organizer profile validated.", timestamp: "2026-07-08 14:25" },
        { id: "h3", user: "Priya Nair", role: "Auditor", action: "Document Review Started", detail: "Began reviewing permit and contract documents.", timestamp: "2026-07-09 10:00" },
        { id: "h4", user: "Priya Nair", role: "Auditor", action: "Document Verified", detail: "venue-permit-2026.pdf verified successfully.", timestamp: "2026-07-09 11:30" },
        { id: "h5", user: "Marcus Chen", role: "Organizer", action: "Document Uploaded", detail: "artist-agreement-headliner.pdf uploaded.", timestamp: "2026-07-09 14:00" },
      ],
      versions: [
        { version: 1, changedBy: "Marcus Chen", timestamp: "2026-07-05 09:00", summary: "Initial event draft created." },
        { version: 2, changedBy: "Marcus Chen", timestamp: "2026-07-07 16:30", summary: "Venue details and ticket tiers updated." },
        { version: 3, changedBy: "Marcus Chen", timestamp: "2026-07-08 14:20", summary: "Final submission with all documents." },
      ],
    },
    revisions: [],
    complianceHistory: {
      previousAudits: 3,
      previousViolations: 1,
      previousRevisions: 2,
      previousApprovedEvents: 2,
    },
    notes: "Police permit and fire dept permit still missing. Vendor MerchHub contract rejected due to no business registration.",
  },
  {
    id: "SUB-3022",
    eventName: "Global Tech Summit 2026",
    organizerName: "Summit Live Events",
    organizerAvatar: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=100&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80",
    category: "Conference",
    submittedAt: "2026-07-07 09:05",
    lastUpdated: "2026-07-09 08:00",
    stage: "Event Validation",
    status: "Pending",
    riskLevel: "Low",
    complianceScore: 91,
    missingDocs: 0,
    assignedAuditor: "Priya Nair",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "moscone-center-contract.pdf", category: "Vendor & Venue Contracts", status: "VERIFIED", uploadDate: "2026-07-01", expiredDate: "2026-12-31", uploadedBy: "Summit Admin" },
      { name: "insurance-certificate.pdf", category: "Insurance", status: "VERIFIED", uploadDate: "2026-07-01", uploadedBy: "Summit Admin" },
      { name: "police-permit-sf.pdf", category: "Permits & Licenses", status: "VERIFIED", uploadDate: "2026-07-03", uploadedBy: "Summit Admin" },
    ],
    venue: "Moscone Center, SF",
    date: "2026-10-02",
    capacity: 1800,
    ticketSold: 1540,
    organizerDetail: {
      companyName: "Summit Live Events Inc.",
      businessLicense: "BL-2023-CA-00110",
      pic: "Sarah Tanaka",
      email: "sarah@summitlive.com",
      phone: "+1 (415) 820-3311",
      address: "747 Howard St, San Francisco CA 94103",
    },
    venueDetail: {
      name: "Moscone Center",
      address: "747 Howard St, San Francisco, CA 94103",
      capacity: 2000,
      manager: "Moscone Center Operations",
      contact: "+1 (415) 974-4000",
      website: "moscone.com",
      googleMaps: "https://maps.google.com/?q=Moscone+Center+San+Francisco",
      complianceScore: 96,
      checklist: [
        { label: "Venue Ownership Verified", done: true },
        { label: "Maximum Capacity Verified", done: true },
        { label: "Seating Configuration Valid", done: true },
        { label: "Emergency Exit Verified", done: true },
        { label: "Fire Safety", done: true },
        { label: "Crowd Flow Validation", done: true },
        { label: "Acoustic Safety", done: true },
        { label: "Structural Safety", done: true },
        { label: "Parking Area", done: true },
        { label: "Accessibility", done: true },
      ],
    },
    logistics: {
      vendorCount: 5,
      securityCount: 30,
      medicalTeam: 4,
      emergencyTeam: 2,
      vendors: [
        { name: "SF AV Solutions", category: "Sound", status: "Verified", contact: "+1 415 300 1010" },
        { name: "TechLight Pro", category: "Lighting", status: "Verified", contact: "+1 415 301 2020" },
        { name: "Moscone Catering", category: "Food", status: "Verified", contact: "+1 415 302 3030" },
        { name: "SF SecureTeam", category: "Security", status: "Verified", contact: "+1 415 303 4040" },
        { name: "CleanPro SF", category: "Cleaning", status: "Verified", contact: "+1 415 304 5050" },
      ],
      emergencyPlan: [
        { label: "Ambulance", done: true },
        { label: "Fire Truck", done: true },
        { label: "Emergency Exit", done: true },
        { label: "Evacuation Route", done: true },
        { label: "Assembly Point", done: true },
      ],
    },
    finance: {
      projectedRevenue: 1540000,
      platformFee: 77000,
      gatewayFee: 30800,
      taxAmount: 138600,
      netPayout: 1293600,
      ticketTiers: [
        { category: "VVIP", price: 2500, seats: 50, status: "Sold Out" },
        { category: "VIP", price: 1200, seats: 200, status: "Active" },
        { category: "Regular", price: 600, seats: 1550, status: "Active" },
      ],
      taxConfig: {
        entertainmentTax: 8,
        ppn: 11,
        region: "San Francisco, CA",
        taxPercentage: 19,
        regionMatch: true,
        taxApplied: true,
        ppnApplied: true,
      },
      payout: {
        bank: "Bank of America",
        accountName: "Summit Live Events Inc.",
        accountNumber: "****7702",
        verified: true,
        estimatedPayout: 1293600,
      },
      complianceChecklist: [
        { label: "Ticket Price Verified", done: true },
        { label: "Revenue Calculation", done: true },
        { label: "Platform Fee Applied", done: true },
        { label: "Tax Calculation", done: true },
        { label: "Tax Match", done: true },
      ],
    },
    history: {
      activityTimeline: [
        { id: "h1", user: "Sarah Tanaka", role: "Organizer", action: "Submitted Event", detail: "Initial submission of Global Tech Summit 2026.", timestamp: "2026-07-07 09:05" },
        { id: "h2", user: "System", role: "Auto", action: "Auto Validation Passed", detail: "All sections validated automatically.", timestamp: "2026-07-07 09:10" },
        { id: "h3", user: "Priya Nair", role: "Auditor", action: "All Documents Verified", detail: "All 3 documents verified without issues.", timestamp: "2026-07-08 11:00" },
      ],
      versions: [
        { version: 1, changedBy: "Sarah Tanaka", timestamp: "2026-07-05 08:00", summary: "Initial event draft." },
        { version: 2, changedBy: "Sarah Tanaka", timestamp: "2026-07-07 09:05", summary: "Final submission." },
      ],
    },
    revisions: [],
    complianceHistory: {
      previousAudits: 8,
      previousViolations: 0,
      previousRevisions: 1,
      previousApprovedEvents: 7,
    },
  },
  {
    id: "SUB-3023",
    eventName: "Riverside Jazz Weekend",
    organizerName: "Nightfall Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-07-05 18:40",
    lastUpdated: "2026-07-06 09:00",
    stage: "Submitted",
    status: "Pending",
    riskLevel: "Medium",
    complianceScore: 44,
    missingDocs: 5,
    assignedAuditor: "Priya Nair",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: false },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "riverside-park-permit.pdf", category: "Permits & Licenses", status: "WAITING REVIEW", uploadDate: "2026-07-05", uploadedBy: "Nightfall Admin" },
      { name: "police-permit.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "fire-safety.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "insurance.pdf", category: "Insurance", status: "MISSING" },
      { name: "venue-contract.pdf", category: "Vendor & Venue Contracts", status: "MISSING" },
      { name: "emergency-plan.pdf", category: "Emergency Plan", status: "MISSING" },
    ],
    venue: "Riverside Green, Portland",
    date: "2026-08-22",
    capacity: 1200,
    ticketSold: 620,
    organizerDetail: {
      companyName: "Nightfall Presents Co.",
      businessLicense: "BL-2022-OR-00881",
      pic: "DJ Reyes",
      email: "dj@nightfallpresents.com",
      phone: "+1 (503) 721-0044",
      address: "400 SE Morrison St, Portland OR 97214",
    },
    venueDetail: {
      name: "Riverside Green",
      address: "Tom McCall Waterfront Park, Portland, OR 97201",
      capacity: 1500,
      manager: "Portland Parks & Recreation",
      contact: "+1 (503) 823-7529",
      website: "portlandoregon.gov/parks",
      googleMaps: "https://maps.google.com/?q=Tom+McCall+Waterfront+Park+Portland",
      complianceScore: 45,
      checklist: [
        { label: "Venue Ownership Verified", done: true },
        { label: "Maximum Capacity Verified", done: false },
        { label: "Seating Configuration Valid", done: false },
        { label: "Emergency Exit Verified", done: false },
        { label: "Fire Safety", done: false },
        { label: "Crowd Flow Validation", done: false },
        { label: "Acoustic Safety", done: true },
        { label: "Structural Safety", done: true },
        { label: "Parking Area", done: false },
        { label: "Accessibility", done: false },
      ],
    },
    logistics: {
      vendorCount: 3,
      securityCount: 15,
      medicalTeam: 2,
      emergencyTeam: 1,
      vendors: [
        { name: "PDX Stage Co", category: "Stage", status: "Pending", contact: "+1 503 200 1010" },
        { name: "Rose City Sound", category: "Sound", status: "Pending", contact: "+1 503 201 2020" },
        { name: "Night Catering", category: "Food", status: "Pending", contact: "+1 503 202 3030" },
      ],
      emergencyPlan: [
        { label: "Ambulance", done: false },
        { label: "Fire Truck", done: false },
        { label: "Emergency Exit", done: false },
        { label: "Evacuation Route", done: false },
        { label: "Assembly Point", done: false },
      ],
    },
    finance: {
      projectedRevenue: 111600,
      platformFee: 5580,
      gatewayFee: 2232,
      taxAmount: 10044,
      netPayout: 93744,
      ticketTiers: [
        { category: "VIP", price: 250, seats: 120, status: "Active" },
        { category: "Regular", price: 75, seats: 1080, status: "Active" },
      ],
      taxConfig: {
        entertainmentTax: 8,
        ppn: 11,
        region: "Portland, OR",
        taxPercentage: 9,
        regionMatch: true,
        taxApplied: false,
        ppnApplied: false,
      },
      payout: {
        bank: "Wells Fargo",
        accountName: "Nightfall Presents Co.",
        accountNumber: "****3309",
        verified: false,
        estimatedPayout: 93744,
      },
      complianceChecklist: [
        { label: "Ticket Price Verified", done: true },
        { label: "Revenue Calculation", done: false },
        { label: "Platform Fee Applied", done: true },
        { label: "Tax Calculation", done: false },
        { label: "Tax Match", done: false },
      ],
    },
    history: {
      activityTimeline: [
        { id: "h1", user: "DJ Reyes", role: "Organizer", action: "Submitted Event", detail: "Initial submission of Riverside Jazz Weekend.", timestamp: "2026-07-05 18:40" },
        { id: "h2", user: "System", role: "Auto", action: "Auto Validation Warning", detail: "Venue layout section incomplete.", timestamp: "2026-07-05 18:45" },
      ],
      versions: [
        { version: 1, changedBy: "DJ Reyes", timestamp: "2026-07-04 10:00", summary: "Initial draft." },
        { version: 2, changedBy: "DJ Reyes", timestamp: "2026-07-05 18:40", summary: "Submitted with incomplete venue layout." },
      ],
    },
    revisions: [
      {
        id: "REV-001",
        category: "Venue" as const,
        affectedSection: "Seating Layout",
        priority: "Critical" as const,
        status: "Sent" as const,
        requestedBy: "Priya Nair",
        requestDate: "2026-07-06",
        deadline: "2026-07-07",
        title: "Venue Layout Incomplete",
        description: "The venue capacity zones and crowd flow paths have not been mapped. Please provide a detailed floor plan with all sections clearly labeled.",
        requiredAction: "Upload a full venue floor plan showing all zones, emergency exits, seating sections, and crowd flow paths. Ensure capacity per zone is clearly marked.",
        severity: "Critical" as const,
        area: "Venue" as const,
        revisionTimeline: [
          { id: "rt1", actor: "Priya Nair", role: "Auditor", action: "Revision Created", timestamp: "2026-07-06 09:00" },
          { id: "rt2", actor: "DJ Reyes", role: "Organizer", action: "Organizer Viewed", timestamp: "2026-07-06 11:30" },
        ],
      },
    ],
    complianceHistory: {
      previousAudits: 2,
      previousViolations: 2,
      previousRevisions: 3,
      previousApprovedEvents: 1,
    },
    notes: "Venue layout section incomplete — zones not mapped to capacity.",
  },
  {
    id: "SUB-3018",
    eventName: "Executive Leadership Retreat",
    organizerName: "CrowdFlow Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=150&auto=format&fit=crop",
    bannerUrl: "https://images.unsplash.com/photo-1560439514-4e9645039924?w=800&auto=format&fit=crop&q=80",
    category: "Conference",
    submittedAt: "2026-06-29 11:15",
    lastUpdated: "2026-07-02 15:00",
    stage: "Final Approval",
    status: "Approved",
    riskLevel: "Low",
    complianceScore: 98,
    missingDocs: 0,
    assignedAuditor: "Priya Nair",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "retreat-center-contract.pdf", category: "Vendor & Venue Contracts", status: "VERIFIED", uploadDate: "2026-06-29", expiredDate: "2026-12-31", uploadedBy: "CrowdFlow Admin" },
      { name: "insurance-executive.pdf", category: "Insurance", status: "VERIFIED", uploadDate: "2026-06-29", uploadedBy: "CrowdFlow Admin" },
    ],
    venue: "Cascade Lodge, WA",
    date: "2026-08-01",
    capacity: 150,
    ticketSold: 148,
    organizerDetail: {
      companyName: "CrowdFlow Presents Inc.",
      businessLicense: "BL-2021-WA-00203",
      pic: "Alex Kim",
      email: "alex@crowdflowpresents.com",
      phone: "+1 (206) 490-2211",
      address: "1201 3rd Ave, Seattle WA 98101",
    },
    venueDetail: {
      name: "Cascade Lodge & Conference Center",
      address: "14200 SE Highway 212, Clackamas, WA 98604",
      capacity: 200,
      manager: "Lodge Director: James Foley",
      contact: "+1 (360) 882-9100",
      website: "cascadelodge.com",
      googleMaps: "https://maps.google.com/?q=Cascade+Lodge+Washington",
      complianceScore: 100,
      checklist: [
        { label: "Venue Ownership Verified", done: true },
        { label: "Maximum Capacity Verified", done: true },
        { label: "Seating Configuration Valid", done: true },
        { label: "Emergency Exit Verified", done: true },
        { label: "Fire Safety", done: true },
        { label: "Crowd Flow Validation", done: true },
        { label: "Acoustic Safety", done: true },
        { label: "Structural Safety", done: true },
        { label: "Parking Area", done: true },
        { label: "Accessibility", done: true },
      ],
    },
    logistics: {
      vendorCount: 2,
      securityCount: 8,
      medicalTeam: 2,
      emergencyTeam: 1,
      vendors: [
        { name: "Cascade AV", category: "Sound", status: "Verified", contact: "+1 360 200 1010" },
        { name: "Lodge Catering", category: "Food", status: "Verified", contact: "+1 360 201 2020" },
      ],
      emergencyPlan: [
        { label: "Ambulance", done: true },
        { label: "Fire Truck", done: true },
        { label: "Emergency Exit", done: true },
        { label: "Evacuation Route", done: true },
        { label: "Assembly Point", done: true },
      ],
    },
    finance: {
      projectedRevenue: 148000,
      platformFee: 7400,
      gatewayFee: 2960,
      taxAmount: 13320,
      netPayout: 124320,
      ticketTiers: [
        { category: "VVIP", price: 1200, seats: 20, status: "Sold Out" },
        { category: "VIP", price: 800, seats: 130, status: "Sold Out" },
      ],
      taxConfig: {
        entertainmentTax: 9,
        ppn: 11,
        region: "Washington State",
        taxPercentage: 10,
        regionMatch: true,
        taxApplied: true,
        ppnApplied: true,
      },
      payout: {
        bank: "US Bank",
        accountName: "CrowdFlow Presents Inc.",
        accountNumber: "****8821",
        verified: true,
        estimatedPayout: 124320,
      },
      complianceChecklist: [
        { label: "Ticket Price Verified", done: true },
        { label: "Revenue Calculation", done: true },
        { label: "Platform Fee Applied", done: true },
        { label: "Tax Calculation", done: true },
        { label: "Tax Match", done: true },
      ],
    },
    history: {
      activityTimeline: [
        { id: "h1", user: "Alex Kim", role: "Organizer", action: "Submitted Event", detail: "Retreat submitted for review.", timestamp: "2026-06-29 11:15" },
        { id: "h2", user: "System", role: "Auto", action: "Auto Validation Passed", detail: "All sections valid.", timestamp: "2026-06-29 11:20" },
        { id: "h3", user: "Priya Nair", role: "Auditor", action: "Approved", detail: "All documents verified, event approved.", timestamp: "2026-07-02 15:00" },
      ],
      versions: [
        { version: 1, changedBy: "Alex Kim", timestamp: "2026-06-28 09:00", summary: "Initial creation." },
        { version: 2, changedBy: "Alex Kim", timestamp: "2026-06-29 11:15", summary: "Final submission." },
      ],
    },
    revisions: [],
    complianceHistory: {
      previousAudits: 5,
      previousViolations: 0,
      previousRevisions: 0,
      previousApprovedEvents: 5,
    },
  },
  {
    id: "SUB-3011",
    eventName: "Underground Bass Collective",
    organizerName: "Nightfall Presents",
    organizerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    bannerUrl: "https://images.unsplash.com/photo-1571151424566-5f8e3cfa7ae1?w=800&auto=format&fit=crop&q=80",
    category: "Festival",
    submittedAt: "2026-06-20 20:00",
    lastUpdated: "2026-06-25 16:00",
    stage: "Document Verification",
    status: "Rejected",
    riskLevel: "Critical",
    complianceScore: 22,
    missingDocs: 4,
    assignedAuditor: "Priya Nair",
    checklist: [
      { label: "Event Info", done: true },
      { label: "Venue Layout", done: true },
      { label: "Organizer Profile", done: true },
      { label: "Ticket Configuration", done: true },
    ],
    documents: [
      { name: "warehouse-lease.pdf", category: "Vendor & Venue Contracts", status: "REJECTED", uploadDate: "2026-06-19", uploadedBy: "Nightfall Admin" },
      { name: "police-permit.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "fire-dept-permit.pdf", category: "Permits & Licenses", status: "MISSING" },
      { name: "insurance.pdf", category: "Insurance", status: "MISSING" },
      { name: "emergency-plan.pdf", category: "Emergency Plan", status: "MISSING" },
    ],
    venue: "Old Freight Warehouse, Brooklyn",
    date: "2026-07-30",
    capacity: 800,
    ticketSold: 0,
    organizerDetail: {
      companyName: "Nightfall Presents Co.",
      businessLicense: "BL-2022-OR-00881",
      pic: "DJ Reyes",
      email: "dj@nightfallpresents.com",
      phone: "+1 (503) 721-0044",
      address: "400 SE Morrison St, Portland OR 97214",
    },
    venueDetail: {
      name: "Old Freight Warehouse",
      address: "120 Beard St, Brooklyn NY 11231",
      capacity: 900,
      manager: "Industrial Properties NYC LLC",
      contact: "+1 (718) 400-1100",
      website: "oldfreightwarehouse.com",
      googleMaps: "https://maps.google.com/?q=120+Beard+St+Brooklyn",
      complianceScore: 18,
      checklist: [
        { label: "Venue Ownership Verified", done: false },
        { label: "Maximum Capacity Verified", done: false },
        { label: "Seating Configuration Valid", done: false },
        { label: "Emergency Exit Verified", done: false },
        { label: "Fire Safety", done: false },
        { label: "Crowd Flow Validation", done: false },
        { label: "Acoustic Safety", done: true },
        { label: "Structural Safety", done: false },
        { label: "Parking Area", done: false },
        { label: "Accessibility", done: false },
      ],
    },
    logistics: {
      vendorCount: 2,
      securityCount: 10,
      medicalTeam: 1,
      emergencyTeam: 0,
      vendors: [
        { name: "BK Stage Crew", category: "Stage", status: "Pending", contact: "+1 718 200 1010" },
        { name: "Underground Sound", category: "Sound", status: "Pending", contact: "+1 718 201 2020" },
      ],
      emergencyPlan: [
        { label: "Ambulance", done: false },
        { label: "Fire Truck", done: false },
        { label: "Emergency Exit", done: false },
        { label: "Evacuation Route", done: false },
        { label: "Assembly Point", done: false },
      ],
    },
    finance: {
      projectedRevenue: 72000,
      platformFee: 3600,
      gatewayFee: 1440,
      taxAmount: 6480,
      netPayout: 60480,
      ticketTiers: [
        { category: "Festival", price: 90, seats: 800, status: "Active" },
      ],
      taxConfig: {
        entertainmentTax: 9,
        ppn: 11,
        region: "Brooklyn, NY",
        taxPercentage: 18,
        regionMatch: false,
        taxApplied: false,
        ppnApplied: false,
      },
      payout: {
        bank: "Chase",
        accountName: "Nightfall Presents Co.",
        accountNumber: "****5532",
        verified: false,
        estimatedPayout: 60480,
      },
      complianceChecklist: [
        { label: "Ticket Price Verified", done: true },
        { label: "Revenue Calculation", done: false },
        { label: "Platform Fee Applied", done: false },
        { label: "Tax Calculation", done: false },
        { label: "Tax Match", done: false },
      ],
    },
    history: {
      activityTimeline: [
        { id: "h1", user: "DJ Reyes", role: "Organizer", action: "Submitted Event", detail: "Submitted Underground Bass Collective.", timestamp: "2026-06-20 20:00" },
        { id: "h2", user: "Priya Nair", role: "Auditor", action: "Rejected", detail: "Venue lease document expired. Event rejected.", timestamp: "2026-06-25 16:00" },
      ],
      versions: [
        { version: 1, changedBy: "DJ Reyes", timestamp: "2026-06-18 15:00", summary: "Initial submission." },
      ],
    },
    revisions: [
      {
        id: "REV-002",
        category: "Documents" as const,
        affectedSection: "Vendor Contract",
        priority: "Critical" as const,
        status: "Rejected" as const,
        requestedBy: "Priya Nair",
        requestDate: "2026-06-24",
        deadline: "2026-06-28",
        title: "Venue Lease Expired",
        description: "The warehouse-lease.pdf document expired on 2026-05-01, prior to the event date. A valid, renewed lease must be submitted.",
        requiredAction: "Submit a renewed venue lease agreement valid through at least 2026-08-01. The lease must include venue name, capacity limits, and event organizer signature.",
        severity: "Critical" as const,
        area: "Document" as const,
        revisionTimeline: [
          { id: "rt1", actor: "Priya Nair", role: "Auditor", action: "Revision Created", timestamp: "2026-06-24 14:00" },
          { id: "rt2", actor: "DJ Reyes", role: "Organizer", action: "Organizer Viewed", timestamp: "2026-06-24 18:00" },
          { id: "rt3", actor: "Priya Nair", role: "Auditor", action: "Revision Rejected — Event Rejected", timestamp: "2026-06-25 16:00" },
        ],
      },
    ],
    complianceHistory: {
      previousAudits: 2,
      previousViolations: 2,
      previousRevisions: 3,
      previousApprovedEvents: 1,
    },
    notes: "Venue lease document expired prior to event date. Requires renewed lease before resubmission.",
  },
];

export const INITIAL_DOCUMENT_REVIEWS: DocumentReview[] = [
  { id: "DOC-501", fileName: "vendor-contract-catering.pdf", category: "Vendor & Venue Contracts", eventName: "Neon Nights Festival", organizerName: "Aurora Live Events", uploadedAt: "2026-07-08", status: "WAITING REVIEW" },
  { id: "DOC-502", fileName: "riverside-park-permit.pdf", category: "Permits & Licenses", eventName: "Riverside Jazz Weekend", organizerName: "Nightfall Presents", uploadedAt: "2026-07-05", status: "WAITING REVIEW" },
  { id: "DOC-503", fileName: "artist-agreement-headliner.pdf", category: "Artist & Talent Agreements", eventName: "Neon Nights Festival", organizerName: "Aurora Live Events", uploadedAt: "2026-07-06", status: "READY" },
  { id: "DOC-499", fileName: "moscone-center-contract.pdf", category: "Vendor & Venue Contracts", eventName: "Global Tech Summit 2026", organizerName: "Summit Live Events", uploadedAt: "2026-07-01", status: "VERIFIED" },
  { id: "DOC-498", fileName: "insurance-certificate.pdf", category: "Supporting Documents", eventName: "Global Tech Summit 2026", organizerName: "Summit Live Events", uploadedAt: "2026-07-01", status: "VERIFIED" },
  { id: "DOC-490", fileName: "warehouse-lease.pdf", category: "Vendor & Venue Contracts", eventName: "Underground Bass Collective", organizerName: "Nightfall Presents", uploadedAt: "2026-06-19", status: "REJECTED" },
];

export const ACTIVITY_LOG: AuditorActivity[] = [
  { id: "act-1", actor: "You", action: "Approved", detail: "Executive Leadership Retreat cleared final approval and was published.", timestamp: "2h ago" },
  { id: "act-2", actor: "You", action: "Rejected", detail: "Underground Bass Collective rejected — expired venue lease.", timestamp: "1d ago" },
  { id: "act-3", actor: "System", action: "Submitted", detail: "Riverside Jazz Weekend entered the review queue.", timestamp: "2d ago" },
  { id: "act-4", actor: "You", action: "Verified", detail: "Insurance certificate confirmed for Global Tech Summit 2026.", timestamp: "3d ago" },
];

import { OrganizerVerification, PayoutRequest } from "./types";

export const INITIAL_ORGANIZERS: OrganizerVerification[] = [
  {
    id: "ORG-1001",
    name: "Aurora Live Events",
    companyName: "Aurora Live Events LLC",
    logo: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80",
    status: "Pending",
    registrationDate: "2026-07-01",
    lastActivity: "2026-07-09 14:00",
    province: "DKI Jakarta",
    businessType: "PT / Limited Liability",
    riskScore: 25,
    riskCategory: "Low",
    companyType: "Event Organizer / Agency",
    businessLicense: "NIB-2024-91283",
    npwp: "01.234.567.8-012.000",
    address: "Sudirman Central Business District Lot 18, Jakarta Selatan",
    registrationNumber: "AHU-001239-AH.01.01",
    picName: "Marcus Chen",
    picPosition: "Managing Director",
    picEmail: "marcus@auroralive.com",
    picPhone: "+62 812-3456-7890",
    picNationalId: "3174091234560002",
    picSelfieUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100",
    industry: "Creative Industries",
    eventCategory: "Music Concerts & Festivals",
    yearsInBusiness: 4,
    previousEventsCount: 12,
    estimatedAnnualRevenue: 5000000000,
    bankName: "Bank Central Asia (BCA)",
    bankAccountHolder: "PT Aurora Live Selaras",
    bankAccountNumber: "5012394012",
    bankVerificationStatus: "Verified",
    checklist: {
      businessLicenseValid: true,
      npwpValid: true,
      picIdentityVerified: true,
      bankAccountVerified: true,
      addressVerified: true,
      emailVerified: true,
      phoneVerified: true,
    },
    riskAssessment: {
      identityMatch: true,
      companyValidation: true,
      fraudHistory: false,
      duplicateAccount: false,
      suspiciousActivity: false,
    },
    internalNotes: "Company profiles and director identities check out perfectly. Clean track record from prior platforms.",
    organizerFeedback: "",
    history: [
      { action: "Registration Submitted", actor: "Marcus Chen", timestamp: "2026-07-01 10:00", details: "Organizer account created and initial profile uploaded." },
      { action: "Email Verified", actor: "System", timestamp: "2026-07-01 10:05", details: "Verification link clicked." },
      { action: "Bank Verified", actor: "System", timestamp: "2026-07-02 09:00", details: "BCA host-to-host bank account name validation matches perfectly." }
    ]
  },
  {
    id: "ORG-1002",
    name: "Summit Live Events",
    companyName: "Summit Live Events Inc.",
    logo: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=100&auto=format&fit=crop&q=80",
    status: "Verified",
    registrationDate: "2026-06-15",
    lastActivity: "2026-07-08 11:00",
    province: "Jawa Barat",
    businessType: "CV / Partnership",
    riskScore: 10,
    riskCategory: "Low",
    companyType: "Corporate Conference Agency",
    businessLicense: "NIB-2023-40129",
    npwp: "02.345.678.9-401.000",
    address: "Jl. Diponegoro No. 22, Bandung",
    registrationNumber: "AHU-009183-AH.01.02",
    picName: "Sarah Tanaka",
    picPosition: "Operations Manager",
    picEmail: "sarah@summitlive.com",
    picPhone: "+62 811-9283-401",
    picNationalId: "3273019876540001",
    picSelfieUrl: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=100",
    industry: "Professional Services",
    eventCategory: "Tech & Corporate Summits",
    yearsInBusiness: 6,
    previousEventsCount: 25,
    estimatedAnnualRevenue: 8000000000,
    bankName: "Bank Mandiri",
    bankAccountHolder: "CV Summit Live Bandung",
    bankAccountNumber: "131002930194",
    bankVerificationStatus: "Verified",
    checklist: {
      businessLicenseValid: true,
      npwpValid: true,
      picIdentityVerified: true,
      bankAccountVerified: true,
      addressVerified: true,
      emailVerified: true,
      phoneVerified: true,
    },
    riskAssessment: {
      identityMatch: true,
      companyValidation: true,
      fraudHistory: false,
      duplicateAccount: false,
      suspiciousActivity: false,
    },
    internalNotes: "Sarah Tanaka verified via e-KTP validation API. Corporate history is clear.",
    organizerFeedback: "Verification approved. Full console features unlocked.",
    history: [
      { action: "Account Created", actor: "Sarah Tanaka", timestamp: "2026-06-15 08:00", details: "Initial profile created." },
      { action: "Compliance Audit Passed", actor: "Priya Nair", timestamp: "2026-06-16 14:00", details: "All NIB & NPWP documents manually verified." },
      { action: "Organizer Verified", actor: "Priya Nair", timestamp: "2026-06-16 14:05", details: "Account set to Verified." }
    ]
  },
  {
    id: "ORG-1003",
    name: "Nightfall Presents",
    companyName: "Nightfall Presents Co.",
    logo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80",
    status: "Need Revision",
    registrationDate: "2026-07-03",
    lastActivity: "2026-07-06 10:00",
    province: "Bali",
    businessType: "PT / Limited Liability",
    riskScore: 55,
    riskCategory: "Medium",
    companyType: "Promoter & Concert Agency",
    businessLicense: "NIB-2025-00192",
    npwp: "03.456.789.0-901.000",
    address: "Jl. Sunset Road No. 88, Kuta, Bali",
    registrationNumber: "AHU-010293-AH.01.01",
    picName: "DJ Reyes",
    picPosition: "Owner / Director",
    picEmail: "dj@nightfallpresents.com",
    picPhone: "+62 813-9028-1100",
    picNationalId: "5103029102830002",
    picSelfieUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    industry: "Entertainment & Leisure",
    eventCategory: "Nightlife, DJ Shows & Festivals",
    yearsInBusiness: 2,
    previousEventsCount: 5,
    estimatedAnnualRevenue: 2000000000,
    bankName: "Bank Negara Indonesia (BNI)",
    bankAccountHolder: "Reyes Nightfall Promindo",
    bankAccountNumber: "0901239102",
    bankVerificationStatus: "Pending",
    checklist: {
      businessLicenseValid: true,
      npwpValid: false,
      picIdentityVerified: true,
      bankAccountVerified: false,
      addressVerified: true,
      emailVerified: true,
      phoneVerified: true,
    },
    riskAssessment: {
      identityMatch: true,
      companyValidation: false,
      fraudHistory: false,
      duplicateAccount: true,
      suspiciousActivity: false,
    },
    internalNotes: "NPWP name doesn't match Limited Liability company registry. Bank details verification pending. Duplicate account flagged with retired ORG-881 account.",
    organizerFeedback: "Nama NPWP tidak sesuai dengan Nama Perusahaan PT yang didaftarkan. Mohon unggah dokumen NPWP terbaru.",
    history: [
      { action: "Account Registered", actor: "DJ Reyes", timestamp: "2026-07-03 14:00", details: "Profile uploaded." },
      { action: "Revision Requested", actor: "Priya Nair", timestamp: "2026-07-05 10:00", details: "Requested updated NPWP card." }
    ]
  }
];

export const INITIAL_PAYOUTS: PayoutRequest[] = [
  {
    id: "PAY-9001",
    organizerName: "Aurora Live Events",
    organizerEmail: "marcus@auroralive.com",
    eventName: "Neon Nights Festival",
    eventDate: "2026-09-12",
    venue: "Zilker Park, Austin",
    completionStatus: "Completed",
    revenue: 920000,
    netRevenue: 772800,
    requestedAmount: 772800,
    requestDate: "2026-09-13",
    status: "Pending",
    salesSummary: {
      ticketsSold: 1840,
      grossRevenue: 920000,
      platformFee: 46000,
      paymentGatewayFee: 18400,
      entertainmentTax: 82800,
      vat: 0,
      refundAmount: 0,
      chargebackAmount: 0,
      netRevenue: 772800
    },
    financialChecklist: {
      revenueMatch: true,
      ticketSalesMatch: true,
      refundCalculated: true,
      chargebackApplied: true,
      platformFeeCorrect: true,
      taxCorrect: true,
      netRevenueCorrect: true
    },
    complianceChecklist: {
      eventApproved: true,
      organizerVerified: true,
      requiredDocumentsComplete: true,
      noActiveInvestigation: true,
      noPendingRevision: true
    },
    bankName: "JP Morgan Chase",
    bankAccountNumber: "****4821",
    bankAccountHolder: "Aurora Live Events LLC",
    bankVerificationStatus: "Verified",
    fraudDetection: {
      duplicatePayout: false,
      suspiciousRevenue: false,
      unusualRefundRate: false,
      highChargeback: false,
      multipleBankChanges: false,
      abnormalTicketSales: false,
      hasAlert: false
    },
    internalNotes: "Event successfully completed with no complaints or outstanding chargebacks. Revenue verification matches gateways.",
    financeNotes: "",
    timeline: [
      { stage: "Request Submitted", actor: "Marcus Chen", timestamp: "2026-09-13 09:00", details: "Payout request for $772,800 generated automatically upon event completion." },
      { stage: "Finance Validation", actor: "System", timestamp: "2026-09-13 09:05", details: "Gateway audit records verified against platform ticketing tables." }
    ]
  },
  {
    id: "PAY-9002",
    organizerName: "Nightfall Presents",
    organizerEmail: "dj@nightfallpresents.com",
    eventName: "Riverside Jazz Weekend",
    eventDate: "2026-08-22",
    venue: "Riverside Green, Portland",
    completionStatus: "Completed",
    revenue: 111600,
    netRevenue: 93744,
    requestedAmount: 93744,
    requestDate: "2026-08-23",
    status: "On Hold",
    salesSummary: {
      ticketsSold: 620,
      grossRevenue: 111600,
      platformFee: 5580,
      paymentGatewayFee: 2232,
      entertainmentTax: 10044,
      vat: 0,
      refundAmount: 0,
      chargebackAmount: 22000,
      netRevenue: 71744
    },
    financialChecklist: {
      revenueMatch: true,
      ticketSalesMatch: true,
      refundCalculated: true,
      chargebackApplied: false,
      platformFeeCorrect: true,
      taxCorrect: true,
      netRevenueCorrect: false
    },
    complianceChecklist: {
      eventApproved: true,
      organizerVerified: true,
      requiredDocumentsComplete: true,
      noActiveInvestigation: false,
      noPendingRevision: true
    },
    bankName: "Wells Fargo",
    bankAccountNumber: "****3309",
    bankAccountHolder: "Nightfall Presents Co.",
    bankVerificationStatus: "Verified",
    fraudDetection: {
      duplicatePayout: false,
      suspiciousRevenue: false,
      unusualRefundRate: true,
      highChargeback: true,
      multipleBankChanges: false,
      abnormalTicketSales: false,
      hasAlert: true,
      alertMessage: "High Chargeback Alert: $22,000 in customer chargebacks filed after the event due to headliner no-show."
    },
    internalNotes: "Payout held because of consumer disputes regarding headliner cancellations. Active investigation pending review by compliance officer.",
    financeNotes: "Adjusted net payout must deduct disputed ticket chargebacks.",
    timeline: [
      { stage: "Request Submitted", actor: "DJ Reyes", timestamp: "2026-08-23 10:00", details: "Payout request generated." },
      { stage: "Placed On Hold", actor: "Priya Nair", timestamp: "2026-08-24 11:00", details: "Auditor placed payout on hold due to chargeback triggers." }
    ]
  }
];

